### ISSUE TITLE
Creating MessagingProfile doesn't support whitelisted destinations

### ISSUE THREAD

**Issue by alexisromero-toast** [team-telnyx/telnyx-java#58]
The [CreateMessagingProfileRequest](https://github.com/team-telnyx/telnyx-java/blob/f7faa034efaef07638e401ca5d8360ecb95cfb1b/src/main/java/com/telnyx/sdk/model/CreateMessagingProfileRequest.java) object that is used to create messaging profiles doesn't support `whitelisted_destinations` and according to the [documentation](https://developers.telnyx.com/api/messaging/create-messaging-profile), it should.

**Comment by ramnish** [comment]
@ADandyGuyInSpace Can you please update this SDK with latest API specs please? Since the March 1 update, CreateMessageProfileRequest call is broken (whitelisted_destinations missing). Thank you

**Comment by dmmc12** [comment]
Hello @ramnish @alexisromero-toast 

A feature parity update has been released in `3.6.0` which should include the latest API specs as well as the changes with the whitelisted destinations for messaging profile creation. 

We will await your feedback before we close this issue. 

Thank you.

**Comment by alexisromero-toast** [comment]
Hi @dmmc12!

I don't see the whitelisted destinations added yet in the `3.6.0` version. How would you normally do that request?

The way we use it is similar to this [example](https://github.com/team-telnyx/telnyx-java/blob/399fad69286265b2e60b17eeef9c5d73860b1fde/docs/MessagingTollfreeVerificationApi.md#example-3)
```java
// Import classes:
import com.telnyx.sdk.ApiClient;
import com.telnyx.sdk.ApiException;
import com.telnyx.sdk.Configuration;
import com.telnyx.sdk.auth.*;
import com.telnyx.sdk.model.*;
import com.telnyx.sdk.api.MessagingTollfreeVerificationApi;

public class Example {
    public static void main(String[] args) {
        ApiClient defaultClient = Configuration.getDefaultApiClient();
        defaultClient.setBasePath("https://api.telnyx.com/v2");
        
        // Configure HTTP bearer authorization: bearerAuth
        HttpBearerAuth bearerAuth = (HttpBearerAuth) defaultClient.getAuthentication("bearerAuth");
        bearerAuth.setBearerToken("BEARER TOKEN");

        MessagingTollfreeVerificationApi apiInstance = new MessagingTollfreeVerificationApi(defaultClient);
        TFVerificationRequest tfVerificationRequest = new TFVerificationRequest(); // TFVerificationRequest | 
        try {
            VerificationRequestEgress result = apiInstance.submitVerificationRequest(tfVerificationRequest);
            System.out.println(result);
        } catch (ApiException e) {
            System.err.println("Exception when calling MessagingTollfreeVerificationApi#submitVerificationRequest");
            System.err.println("Status code: " + e.getCode());
            System.err.println("Reason: " + e.getResponseBody());
            System.err.println("Response headers: " + e.getResponseHeaders());
            e.printStackTrace();
        }
    }
}
```

We send the [TFVerificationRequest](https://github.com/team-telnyx/telnyx-java/blob/399fad69286265b2e60b17eeef9c5d73860b1fde/src/main/java/com/telnyx/sdk/model/TFVerificationRequest.java#L45) and it doesn't look like the whitelisted destinations have been added there.

**Comment by alexisromero-toast** [comment]
I was able to create a messaging profile using the `whitelistedDestinations` using version `3.6.0` 👍

**Comment by ramnish** [comment]
Thank you @dmmc12 . CreateMessageProfileRequest is working fine in 3.6.0.

**Comment by alexisromero-toast** [comment]
This is working now, thanks @dmmc12

**Comment by dmmc12** [comment]
Thank you for the confirmation @alexisromero-toast happy messaging!
